export type Maybe<T> = T;
export type InputMaybe<T> = T;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  Cursor: { input: any; output: any; }
  DateOnly: { input: string; output: string; }
  JSON: { input: any; output: any; }
  NullString: { input: any; output: any; }
  Time: { input: string; output: string; }
  TimeOnly: { input: string; output: string; }
};

export type CartProduct = Node & {
  __typename?: 'CartProduct';
  createdAt: Scalars['Time']['output'];
  id: Scalars['ID']['output'];
  product: Product;
  productID: Scalars['ID']['output'];
  quantity: Scalars['Int']['output'];
  toDeliver: Scalars['Boolean']['output'];
  updatedAt: Scalars['Time']['output'];
  user: Member;
  userID: Scalars['ID']['output'];
  variant: Scalars['String']['output'];
};

/** A connection to a list of items. */
export type CartProductConnection = {
  __typename?: 'CartProductConnection';
  /** A list of edges. */
  edges: Maybe<Array<Maybe<CartProductEdge>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  /** Identifies the total count of items in the connection. */
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type CartProductEdge = {
  __typename?: 'CartProductEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['Cursor']['output'];
  /** The item at the end of the edge. */
  node: Maybe<CartProduct>;
};

export enum CartProductField {
  CreatedAt = 'createdAt',
  ProductId = 'productID',
  Quantity = 'quantity',
  ToDeliver = 'toDeliver',
  UpdatedAt = 'updatedAt',
  UserId = 'userID',
  Variant = 'variant'
}

/** Ordering options for CartProduct connections */
export type CartProductOrder = {
  /** The ordering direction. */
  direction: OrderDirection;
  /** The field by which to order CartProducts. */
  field: CartProductOrderField;
};

/** Properties by which CartProduct connections can be ordered. */
export enum CartProductOrderField {
  CreatedAt = 'createdAt',
  Id = 'id',
  UpdatedAt = 'updatedAt'
}

/**
 * CartProductWhereInput is used for filtering CartProduct objects.
 * Input was generated by ent.
 */
export type CartProductWhereInput = {
  and: InputMaybe<Array<CartProductWhereInput>>;
  /** created_at field predicates */
  createdAt: InputMaybe<Scalars['Time']['input']>;
  createdAtGT: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE: InputMaybe<Scalars['Time']['input']>;
  createdAtIn: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtLT: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn: InputMaybe<Array<Scalars['Time']['input']>>;
  /** product edge predicates */
  hasProduct: InputMaybe<Scalars['Boolean']['input']>;
  hasProductWith: InputMaybe<Array<ProductWhereInput>>;
  /** user edge predicates */
  hasUser: InputMaybe<Scalars['Boolean']['input']>;
  hasUserWith: InputMaybe<Array<MemberWhereInput>>;
  /** id field predicates */
  id: InputMaybe<Scalars['ID']['input']>;
  idGT: InputMaybe<Scalars['ID']['input']>;
  idGTE: InputMaybe<Scalars['ID']['input']>;
  idIn: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT: InputMaybe<Scalars['ID']['input']>;
  idLTE: InputMaybe<Scalars['ID']['input']>;
  idNEQ: InputMaybe<Scalars['ID']['input']>;
  idNotIn: InputMaybe<Array<Scalars['ID']['input']>>;
  not: InputMaybe<CartProductWhereInput>;
  or: InputMaybe<Array<CartProductWhereInput>>;
  /** product_id field predicates */
  productID: InputMaybe<Scalars['ID']['input']>;
  productIDIn: InputMaybe<Array<Scalars['ID']['input']>>;
  productIDNEQ: InputMaybe<Scalars['ID']['input']>;
  productIDNotIn: InputMaybe<Array<Scalars['ID']['input']>>;
  /** quantity field predicates */
  quantity: InputMaybe<Scalars['Int']['input']>;
  quantityGT: InputMaybe<Scalars['Int']['input']>;
  quantityGTE: InputMaybe<Scalars['Int']['input']>;
  quantityIn: InputMaybe<Array<Scalars['Int']['input']>>;
  quantityLT: InputMaybe<Scalars['Int']['input']>;
  quantityLTE: InputMaybe<Scalars['Int']['input']>;
  quantityNEQ: InputMaybe<Scalars['Int']['input']>;
  quantityNotIn: InputMaybe<Array<Scalars['Int']['input']>>;
  /** to_deliver field predicates */
  toDeliver: InputMaybe<Scalars['Boolean']['input']>;
  toDeliverNEQ: InputMaybe<Scalars['Boolean']['input']>;
  /** updated_at field predicates */
  updatedAt: InputMaybe<Scalars['Time']['input']>;
  updatedAtGT: InputMaybe<Scalars['Time']['input']>;
  updatedAtGTE: InputMaybe<Scalars['Time']['input']>;
  updatedAtIn: InputMaybe<Array<Scalars['Time']['input']>>;
  updatedAtLT: InputMaybe<Scalars['Time']['input']>;
  updatedAtLTE: InputMaybe<Scalars['Time']['input']>;
  updatedAtNEQ: InputMaybe<Scalars['Time']['input']>;
  updatedAtNotIn: InputMaybe<Array<Scalars['Time']['input']>>;
  /** user_id field predicates */
  userID: InputMaybe<Scalars['ID']['input']>;
  userIDIn: InputMaybe<Array<Scalars['ID']['input']>>;
  userIDNEQ: InputMaybe<Scalars['ID']['input']>;
  userIDNotIn: InputMaybe<Array<Scalars['ID']['input']>>;
  /** variant field predicates */
  variant: InputMaybe<Scalars['String']['input']>;
  variantContains: InputMaybe<Scalars['String']['input']>;
  variantContainsFold: InputMaybe<Scalars['String']['input']>;
  variantEqualFold: InputMaybe<Scalars['String']['input']>;
  variantGT: InputMaybe<Scalars['String']['input']>;
  variantGTE: InputMaybe<Scalars['String']['input']>;
  variantHasPrefix: InputMaybe<Scalars['String']['input']>;
  variantHasSuffix: InputMaybe<Scalars['String']['input']>;
  variantIn: InputMaybe<Array<Scalars['String']['input']>>;
  variantLT: InputMaybe<Scalars['String']['input']>;
  variantLTE: InputMaybe<Scalars['String']['input']>;
  variantNEQ: InputMaybe<Scalars['String']['input']>;
  variantNotIn: InputMaybe<Array<Scalars['String']['input']>>;
};

export type Coupon = Node & {
  __typename?: 'Coupon';
  couponCode: Scalars['String']['output'];
  createdAt: Scalars['Time']['output'];
  discountPercentage: Scalars['Int']['output'];
  email: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  redeemed: Scalars['Boolean']['output'];
  redeemedOn: Scalars['Time']['output'];
  updatedAt: Scalars['Time']['output'];
};

/** A connection to a list of items. */
export type CouponConnection = {
  __typename?: 'CouponConnection';
  /** A list of edges. */
  edges: Maybe<Array<Maybe<CouponEdge>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  /** Identifies the total count of items in the connection. */
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type CouponEdge = {
  __typename?: 'CouponEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['Cursor']['output'];
  /** The item at the end of the edge. */
  node: Maybe<Coupon>;
};

export enum CouponField {
  CouponCode = 'couponCode',
  CreatedAt = 'createdAt',
  DiscountPercentage = 'discountPercentage',
  Email = 'email',
  Redeemed = 'redeemed',
  RedeemedOn = 'redeemedOn',
  UpdatedAt = 'updatedAt'
}

/** Ordering options for Coupon connections */
export type CouponOrder = {
  /** The ordering direction. */
  direction: OrderDirection;
  /** The field by which to order Coupons. */
  field: CouponOrderField;
};

/** Properties by which Coupon connections can be ordered. */
export enum CouponOrderField {
  CreatedAt = 'createdAt',
  Id = 'id',
  UpdatedAt = 'updatedAt'
}

/**
 * CouponWhereInput is used for filtering Coupon objects.
 * Input was generated by ent.
 */
export type CouponWhereInput = {
  and: InputMaybe<Array<CouponWhereInput>>;
  /** coupon_code field predicates */
  couponCode: InputMaybe<Scalars['String']['input']>;
  couponCodeContains: InputMaybe<Scalars['String']['input']>;
  couponCodeContainsFold: InputMaybe<Scalars['String']['input']>;
  couponCodeEqualFold: InputMaybe<Scalars['String']['input']>;
  couponCodeGT: InputMaybe<Scalars['String']['input']>;
  couponCodeGTE: InputMaybe<Scalars['String']['input']>;
  couponCodeHasPrefix: InputMaybe<Scalars['String']['input']>;
  couponCodeHasSuffix: InputMaybe<Scalars['String']['input']>;
  couponCodeIn: InputMaybe<Array<Scalars['String']['input']>>;
  couponCodeLT: InputMaybe<Scalars['String']['input']>;
  couponCodeLTE: InputMaybe<Scalars['String']['input']>;
  couponCodeNEQ: InputMaybe<Scalars['String']['input']>;
  couponCodeNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  /** created_at field predicates */
  createdAt: InputMaybe<Scalars['Time']['input']>;
  createdAtGT: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE: InputMaybe<Scalars['Time']['input']>;
  createdAtIn: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtLT: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn: InputMaybe<Array<Scalars['Time']['input']>>;
  /** discount_percentage field predicates */
  discountPercentage: InputMaybe<Scalars['Int']['input']>;
  discountPercentageGT: InputMaybe<Scalars['Int']['input']>;
  discountPercentageGTE: InputMaybe<Scalars['Int']['input']>;
  discountPercentageIn: InputMaybe<Array<Scalars['Int']['input']>>;
  discountPercentageLT: InputMaybe<Scalars['Int']['input']>;
  discountPercentageLTE: InputMaybe<Scalars['Int']['input']>;
  discountPercentageNEQ: InputMaybe<Scalars['Int']['input']>;
  discountPercentageNotIn: InputMaybe<Array<Scalars['Int']['input']>>;
  /** email field predicates */
  email: InputMaybe<Scalars['String']['input']>;
  emailContains: InputMaybe<Scalars['String']['input']>;
  emailContainsFold: InputMaybe<Scalars['String']['input']>;
  emailEqualFold: InputMaybe<Scalars['String']['input']>;
  emailGT: InputMaybe<Scalars['String']['input']>;
  emailGTE: InputMaybe<Scalars['String']['input']>;
  emailHasPrefix: InputMaybe<Scalars['String']['input']>;
  emailHasSuffix: InputMaybe<Scalars['String']['input']>;
  emailIn: InputMaybe<Array<Scalars['String']['input']>>;
  emailLT: InputMaybe<Scalars['String']['input']>;
  emailLTE: InputMaybe<Scalars['String']['input']>;
  emailNEQ: InputMaybe<Scalars['String']['input']>;
  emailNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  /** id field predicates */
  id: InputMaybe<Scalars['ID']['input']>;
  idGT: InputMaybe<Scalars['ID']['input']>;
  idGTE: InputMaybe<Scalars['ID']['input']>;
  idIn: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT: InputMaybe<Scalars['ID']['input']>;
  idLTE: InputMaybe<Scalars['ID']['input']>;
  idNEQ: InputMaybe<Scalars['ID']['input']>;
  idNotIn: InputMaybe<Array<Scalars['ID']['input']>>;
  not: InputMaybe<CouponWhereInput>;
  or: InputMaybe<Array<CouponWhereInput>>;
  /** redeemed field predicates */
  redeemed: InputMaybe<Scalars['Boolean']['input']>;
  redeemedNEQ: InputMaybe<Scalars['Boolean']['input']>;
  /** redeemed_on field predicates */
  redeemedOn: InputMaybe<Scalars['Time']['input']>;
  redeemedOnGT: InputMaybe<Scalars['Time']['input']>;
  redeemedOnGTE: InputMaybe<Scalars['Time']['input']>;
  redeemedOnIn: InputMaybe<Array<Scalars['Time']['input']>>;
  redeemedOnLT: InputMaybe<Scalars['Time']['input']>;
  redeemedOnLTE: InputMaybe<Scalars['Time']['input']>;
  redeemedOnNEQ: InputMaybe<Scalars['Time']['input']>;
  redeemedOnNotIn: InputMaybe<Array<Scalars['Time']['input']>>;
  /** updated_at field predicates */
  updatedAt: InputMaybe<Scalars['Time']['input']>;
  updatedAtGT: InputMaybe<Scalars['Time']['input']>;
  updatedAtGTE: InputMaybe<Scalars['Time']['input']>;
  updatedAtIn: InputMaybe<Array<Scalars['Time']['input']>>;
  updatedAtLT: InputMaybe<Scalars['Time']['input']>;
  updatedAtLTE: InputMaybe<Scalars['Time']['input']>;
  updatedAtNEQ: InputMaybe<Scalars['Time']['input']>;
  updatedAtNotIn: InputMaybe<Array<Scalars['Time']['input']>>;
};

/**
 * CreateCartProductInput is used for create CartProduct object.
 * Input was generated by ent.
 */
export type CreateCartProductInput = {
  createdAt: InputMaybe<Scalars['Time']['input']>;
  productID: Scalars['ID']['input'];
  quantity: Scalars['Int']['input'];
  toDeliver: InputMaybe<Scalars['Boolean']['input']>;
  updatedAt: InputMaybe<Scalars['Time']['input']>;
  userID: Scalars['ID']['input'];
  variant: Scalars['String']['input'];
};

/**
 * CreateCouponInput is used for create Coupon object.
 * Input was generated by ent.
 */
export type CreateCouponInput = {
  couponCode: InputMaybe<Scalars['String']['input']>;
  createdAt: InputMaybe<Scalars['Time']['input']>;
  discountPercentage: InputMaybe<Scalars['Int']['input']>;
  email: Scalars['String']['input'];
  redeemed: InputMaybe<Scalars['Boolean']['input']>;
  redeemedOn: Scalars['Time']['input'];
  updatedAt: InputMaybe<Scalars['Time']['input']>;
};

/**
 * CreateMemberInput is used for create Member object.
 * Input was generated by ent.
 */
export type CreateMemberInput = {
  alternatePhoneNumber: InputMaybe<Scalars['String']['input']>;
  city: InputMaybe<Scalars['String']['input']>;
  createdAt: InputMaybe<Scalars['Time']['input']>;
  deptName: InputMaybe<Scalars['String']['input']>;
  email: Scalars['String']['input'];
  eventName: InputMaybe<Scalars['String']['input']>;
  houseNo: InputMaybe<Scalars['String']['input']>;
  inCartProductIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  landmark: InputMaybe<Scalars['String']['input']>;
  name: Scalars['String']['input'];
  orderIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  orderedProductIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  phoneNumber: InputMaybe<Scalars['String']['input']>;
  pincode: InputMaybe<Scalars['String']['input']>;
  place: InputMaybe<Scalars['String']['input']>;
  profilePicURL: InputMaybe<Scalars['String']['input']>;
  role: InputMaybe<MemberRole>;
  street: InputMaybe<Scalars['String']['input']>;
  updatedAt: InputMaybe<Scalars['Time']['input']>;
};

/**
 * CreateOrderInput is used for create Order object.
 * Input was generated by ent.
 */
export type CreateOrderInput = {
  alternatePhoneNumber: InputMaybe<Scalars['String']['input']>;
  city: InputMaybe<Scalars['String']['input']>;
  createdAt: InputMaybe<Scalars['Time']['input']>;
  email: Scalars['String']['input'];
  houseNo: InputMaybe<Scalars['String']['input']>;
  landmark: InputMaybe<Scalars['String']['input']>;
  orderDate: InputMaybe<Scalars['Time']['input']>;
  orderedProductIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  paidAmount: Scalars['Float']['input'];
  phoneNumber: InputMaybe<Scalars['String']['input']>;
  pincode: InputMaybe<Scalars['String']['input']>;
  place: InputMaybe<Scalars['String']['input']>;
  street: InputMaybe<Scalars['String']['input']>;
  updatedAt: InputMaybe<Scalars['Time']['input']>;
  userID: Scalars['ID']['input'];
};

/**
 * CreateOrderedProductInput is used for create OrderedProduct object.
 * Input was generated by ent.
 */
export type CreateOrderedProductInput = {
  createdAt: InputMaybe<Scalars['Time']['input']>;
  orderID: Scalars['ID']['input'];
  productID: Scalars['ID']['input'];
  quantity: Scalars['Int']['input'];
  status: Scalars['String']['input'];
  toDeliver: InputMaybe<Scalars['Boolean']['input']>;
  updatedAt: InputMaybe<Scalars['Time']['input']>;
  userID: Scalars['ID']['input'];
  variant: Scalars['String']['input'];
};

/**
 * CreateProductImagesInput is used for create ProductImages object.
 * Input was generated by ent.
 */
export type CreateProductImagesInput = {
  createdAt: InputMaybe<Scalars['Time']['input']>;
  imageURL: Scalars['String']['input'];
  productID: Scalars['ID']['input'];
  updatedAt: InputMaybe<Scalars['Time']['input']>;
};

/**
 * CreateProductInput is used for create Product object.
 * Input was generated by ent.
 */
export type CreateProductInput = {
  category: ProductCategory;
  createdAt: InputMaybe<Scalars['Time']['input']>;
  description: InputMaybe<Scalars['String']['input']>;
  imageIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  inCartProductIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  isDeliverable: InputMaybe<Scalars['Boolean']['input']>;
  name: Scalars['String']['input'];
  orderedProductIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  price: Scalars['String']['input'];
  updatedAt: InputMaybe<Scalars['Time']['input']>;
  variantIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  weight: Scalars['Int']['input'];
};

/**
 * CreateProductVariantsInput is used for create ProductVariants object.
 * Input was generated by ent.
 */
export type CreateProductVariantsInput = {
  createdAt: InputMaybe<Scalars['Time']['input']>;
  productID: Scalars['ID']['input'];
  quantity: Scalars['Int']['input'];
  updatedAt: InputMaybe<Scalars['Time']['input']>;
  variant: Scalars['String']['input'];
};

export type LoginResponse = {
  __typename?: 'LoginResponse';
  member: Maybe<Member>;
  token: Maybe<Scalars['String']['output']>;
};

export type Member = Node & {
  __typename?: 'Member';
  alternatePhoneNumber: Maybe<Scalars['String']['output']>;
  city: Maybe<Scalars['String']['output']>;
  createdAt: Scalars['Time']['output'];
  deptName: Maybe<Scalars['String']['output']>;
  email: Scalars['String']['output'];
  eventName: Maybe<Scalars['String']['output']>;
  houseNo: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  inCartProducts: Maybe<Array<CartProduct>>;
  landmark: Maybe<Scalars['String']['output']>;
  name: Scalars['String']['output'];
  orderedProducts: Maybe<Array<OrderedProduct>>;
  orders: Maybe<Array<Order>>;
  phoneNumber: Maybe<Scalars['String']['output']>;
  pincode: Maybe<Scalars['String']['output']>;
  place: Maybe<Scalars['String']['output']>;
  profilePicURL: Maybe<Scalars['String']['output']>;
  role: MemberRole;
  street: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['Time']['output'];
};

/** A connection to a list of items. */
export type MemberConnection = {
  __typename?: 'MemberConnection';
  /** A list of edges. */
  edges: Maybe<Array<Maybe<MemberEdge>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  /** Identifies the total count of items in the connection. */
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type MemberEdge = {
  __typename?: 'MemberEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['Cursor']['output'];
  /** The item at the end of the edge. */
  node: Maybe<Member>;
};

export enum MemberField {
  AlternatePhoneNumber = 'alternatePhoneNumber',
  City = 'city',
  CreatedAt = 'createdAt',
  DeptName = 'deptName',
  Email = 'email',
  EventName = 'eventName',
  HouseNo = 'houseNo',
  Landmark = 'landmark',
  Name = 'name',
  PhoneNumber = 'phoneNumber',
  Pincode = 'pincode',
  Place = 'place',
  ProfilePicUrl = 'profilePicURL',
  Role = 'role',
  Street = 'street',
  UpdatedAt = 'updatedAt'
}

/** Ordering options for Member connections */
export type MemberOrder = {
  /** The ordering direction. */
  direction: OrderDirection;
  /** The field by which to order Members. */
  field: MemberOrderField;
};

/** Properties by which Member connections can be ordered. */
export enum MemberOrderField {
  CreatedAt = 'createdAt',
  Id = 'id',
  UpdatedAt = 'updatedAt'
}

/** MemberRole is enum for the field role */
export enum MemberRole {
  Admin = 'admin',
  OrganizingTeam = 'organizing_team',
  Sales = 'sales',
  Student = 'student'
}

/**
 * MemberWhereInput is used for filtering Member objects.
 * Input was generated by ent.
 */
export type MemberWhereInput = {
  /** alternate_phone_number field predicates */
  alternatePhoneNumber: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberContains: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberContainsFold: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberEqualFold: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberGT: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberGTE: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberHasPrefix: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberHasSuffix: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberIn: InputMaybe<Array<Scalars['String']['input']>>;
  alternatePhoneNumberIsNil: InputMaybe<Scalars['Boolean']['input']>;
  alternatePhoneNumberLT: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberLTE: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberNEQ: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  alternatePhoneNumberNotNil: InputMaybe<Scalars['Boolean']['input']>;
  and: InputMaybe<Array<MemberWhereInput>>;
  /** city field predicates */
  city: InputMaybe<Scalars['String']['input']>;
  cityContains: InputMaybe<Scalars['String']['input']>;
  cityContainsFold: InputMaybe<Scalars['String']['input']>;
  cityEqualFold: InputMaybe<Scalars['String']['input']>;
  cityGT: InputMaybe<Scalars['String']['input']>;
  cityGTE: InputMaybe<Scalars['String']['input']>;
  cityHasPrefix: InputMaybe<Scalars['String']['input']>;
  cityHasSuffix: InputMaybe<Scalars['String']['input']>;
  cityIn: InputMaybe<Array<Scalars['String']['input']>>;
  cityIsNil: InputMaybe<Scalars['Boolean']['input']>;
  cityLT: InputMaybe<Scalars['String']['input']>;
  cityLTE: InputMaybe<Scalars['String']['input']>;
  cityNEQ: InputMaybe<Scalars['String']['input']>;
  cityNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  cityNotNil: InputMaybe<Scalars['Boolean']['input']>;
  /** created_at field predicates */
  createdAt: InputMaybe<Scalars['Time']['input']>;
  createdAtGT: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE: InputMaybe<Scalars['Time']['input']>;
  createdAtIn: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtLT: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn: InputMaybe<Array<Scalars['Time']['input']>>;
  /** dept_name field predicates */
  deptName: InputMaybe<Scalars['String']['input']>;
  deptNameContains: InputMaybe<Scalars['String']['input']>;
  deptNameContainsFold: InputMaybe<Scalars['String']['input']>;
  deptNameEqualFold: InputMaybe<Scalars['String']['input']>;
  deptNameGT: InputMaybe<Scalars['String']['input']>;
  deptNameGTE: InputMaybe<Scalars['String']['input']>;
  deptNameHasPrefix: InputMaybe<Scalars['String']['input']>;
  deptNameHasSuffix: InputMaybe<Scalars['String']['input']>;
  deptNameIn: InputMaybe<Array<Scalars['String']['input']>>;
  deptNameIsNil: InputMaybe<Scalars['Boolean']['input']>;
  deptNameLT: InputMaybe<Scalars['String']['input']>;
  deptNameLTE: InputMaybe<Scalars['String']['input']>;
  deptNameNEQ: InputMaybe<Scalars['String']['input']>;
  deptNameNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  deptNameNotNil: InputMaybe<Scalars['Boolean']['input']>;
  /** email field predicates */
  email: InputMaybe<Scalars['String']['input']>;
  emailContains: InputMaybe<Scalars['String']['input']>;
  emailContainsFold: InputMaybe<Scalars['String']['input']>;
  emailEqualFold: InputMaybe<Scalars['String']['input']>;
  emailGT: InputMaybe<Scalars['String']['input']>;
  emailGTE: InputMaybe<Scalars['String']['input']>;
  emailHasPrefix: InputMaybe<Scalars['String']['input']>;
  emailHasSuffix: InputMaybe<Scalars['String']['input']>;
  emailIn: InputMaybe<Array<Scalars['String']['input']>>;
  emailLT: InputMaybe<Scalars['String']['input']>;
  emailLTE: InputMaybe<Scalars['String']['input']>;
  emailNEQ: InputMaybe<Scalars['String']['input']>;
  emailNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  /** event_name field predicates */
  eventName: InputMaybe<Scalars['String']['input']>;
  eventNameContains: InputMaybe<Scalars['String']['input']>;
  eventNameContainsFold: InputMaybe<Scalars['String']['input']>;
  eventNameEqualFold: InputMaybe<Scalars['String']['input']>;
  eventNameGT: InputMaybe<Scalars['String']['input']>;
  eventNameGTE: InputMaybe<Scalars['String']['input']>;
  eventNameHasPrefix: InputMaybe<Scalars['String']['input']>;
  eventNameHasSuffix: InputMaybe<Scalars['String']['input']>;
  eventNameIn: InputMaybe<Array<Scalars['String']['input']>>;
  eventNameIsNil: InputMaybe<Scalars['Boolean']['input']>;
  eventNameLT: InputMaybe<Scalars['String']['input']>;
  eventNameLTE: InputMaybe<Scalars['String']['input']>;
  eventNameNEQ: InputMaybe<Scalars['String']['input']>;
  eventNameNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  eventNameNotNil: InputMaybe<Scalars['Boolean']['input']>;
  /** in_cart_products edge predicates */
  hasInCartProducts: InputMaybe<Scalars['Boolean']['input']>;
  hasInCartProductsWith: InputMaybe<Array<CartProductWhereInput>>;
  /** ordered_products edge predicates */
  hasOrderedProducts: InputMaybe<Scalars['Boolean']['input']>;
  hasOrderedProductsWith: InputMaybe<Array<OrderedProductWhereInput>>;
  /** orders edge predicates */
  hasOrders: InputMaybe<Scalars['Boolean']['input']>;
  hasOrdersWith: InputMaybe<Array<OrderWhereInput>>;
  /** house_no field predicates */
  houseNo: InputMaybe<Scalars['String']['input']>;
  houseNoContains: InputMaybe<Scalars['String']['input']>;
  houseNoContainsFold: InputMaybe<Scalars['String']['input']>;
  houseNoEqualFold: InputMaybe<Scalars['String']['input']>;
  houseNoGT: InputMaybe<Scalars['String']['input']>;
  houseNoGTE: InputMaybe<Scalars['String']['input']>;
  houseNoHasPrefix: InputMaybe<Scalars['String']['input']>;
  houseNoHasSuffix: InputMaybe<Scalars['String']['input']>;
  houseNoIn: InputMaybe<Array<Scalars['String']['input']>>;
  houseNoIsNil: InputMaybe<Scalars['Boolean']['input']>;
  houseNoLT: InputMaybe<Scalars['String']['input']>;
  houseNoLTE: InputMaybe<Scalars['String']['input']>;
  houseNoNEQ: InputMaybe<Scalars['String']['input']>;
  houseNoNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  houseNoNotNil: InputMaybe<Scalars['Boolean']['input']>;
  /** id field predicates */
  id: InputMaybe<Scalars['ID']['input']>;
  idGT: InputMaybe<Scalars['ID']['input']>;
  idGTE: InputMaybe<Scalars['ID']['input']>;
  idIn: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT: InputMaybe<Scalars['ID']['input']>;
  idLTE: InputMaybe<Scalars['ID']['input']>;
  idNEQ: InputMaybe<Scalars['ID']['input']>;
  idNotIn: InputMaybe<Array<Scalars['ID']['input']>>;
  /** landmark field predicates */
  landmark: InputMaybe<Scalars['String']['input']>;
  landmarkContains: InputMaybe<Scalars['String']['input']>;
  landmarkContainsFold: InputMaybe<Scalars['String']['input']>;
  landmarkEqualFold: InputMaybe<Scalars['String']['input']>;
  landmarkGT: InputMaybe<Scalars['String']['input']>;
  landmarkGTE: InputMaybe<Scalars['String']['input']>;
  landmarkHasPrefix: InputMaybe<Scalars['String']['input']>;
  landmarkHasSuffix: InputMaybe<Scalars['String']['input']>;
  landmarkIn: InputMaybe<Array<Scalars['String']['input']>>;
  landmarkIsNil: InputMaybe<Scalars['Boolean']['input']>;
  landmarkLT: InputMaybe<Scalars['String']['input']>;
  landmarkLTE: InputMaybe<Scalars['String']['input']>;
  landmarkNEQ: InputMaybe<Scalars['String']['input']>;
  landmarkNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  landmarkNotNil: InputMaybe<Scalars['Boolean']['input']>;
  /** name field predicates */
  name: InputMaybe<Scalars['String']['input']>;
  nameContains: InputMaybe<Scalars['String']['input']>;
  nameContainsFold: InputMaybe<Scalars['String']['input']>;
  nameEqualFold: InputMaybe<Scalars['String']['input']>;
  nameGT: InputMaybe<Scalars['String']['input']>;
  nameGTE: InputMaybe<Scalars['String']['input']>;
  nameHasPrefix: InputMaybe<Scalars['String']['input']>;
  nameHasSuffix: InputMaybe<Scalars['String']['input']>;
  nameIn: InputMaybe<Array<Scalars['String']['input']>>;
  nameLT: InputMaybe<Scalars['String']['input']>;
  nameLTE: InputMaybe<Scalars['String']['input']>;
  nameNEQ: InputMaybe<Scalars['String']['input']>;
  nameNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  not: InputMaybe<MemberWhereInput>;
  or: InputMaybe<Array<MemberWhereInput>>;
  /** phone_number field predicates */
  phoneNumber: InputMaybe<Scalars['String']['input']>;
  phoneNumberContains: InputMaybe<Scalars['String']['input']>;
  phoneNumberContainsFold: InputMaybe<Scalars['String']['input']>;
  phoneNumberEqualFold: InputMaybe<Scalars['String']['input']>;
  phoneNumberGT: InputMaybe<Scalars['String']['input']>;
  phoneNumberGTE: InputMaybe<Scalars['String']['input']>;
  phoneNumberHasPrefix: InputMaybe<Scalars['String']['input']>;
  phoneNumberHasSuffix: InputMaybe<Scalars['String']['input']>;
  phoneNumberIn: InputMaybe<Array<Scalars['String']['input']>>;
  phoneNumberIsNil: InputMaybe<Scalars['Boolean']['input']>;
  phoneNumberLT: InputMaybe<Scalars['String']['input']>;
  phoneNumberLTE: InputMaybe<Scalars['String']['input']>;
  phoneNumberNEQ: InputMaybe<Scalars['String']['input']>;
  phoneNumberNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  phoneNumberNotNil: InputMaybe<Scalars['Boolean']['input']>;
  /** pincode field predicates */
  pincode: InputMaybe<Scalars['String']['input']>;
  pincodeContains: InputMaybe<Scalars['String']['input']>;
  pincodeContainsFold: InputMaybe<Scalars['String']['input']>;
  pincodeEqualFold: InputMaybe<Scalars['String']['input']>;
  pincodeGT: InputMaybe<Scalars['String']['input']>;
  pincodeGTE: InputMaybe<Scalars['String']['input']>;
  pincodeHasPrefix: InputMaybe<Scalars['String']['input']>;
  pincodeHasSuffix: InputMaybe<Scalars['String']['input']>;
  pincodeIn: InputMaybe<Array<Scalars['String']['input']>>;
  pincodeIsNil: InputMaybe<Scalars['Boolean']['input']>;
  pincodeLT: InputMaybe<Scalars['String']['input']>;
  pincodeLTE: InputMaybe<Scalars['String']['input']>;
  pincodeNEQ: InputMaybe<Scalars['String']['input']>;
  pincodeNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  pincodeNotNil: InputMaybe<Scalars['Boolean']['input']>;
  /** place field predicates */
  place: InputMaybe<Scalars['String']['input']>;
  placeContains: InputMaybe<Scalars['String']['input']>;
  placeContainsFold: InputMaybe<Scalars['String']['input']>;
  placeEqualFold: InputMaybe<Scalars['String']['input']>;
  placeGT: InputMaybe<Scalars['String']['input']>;
  placeGTE: InputMaybe<Scalars['String']['input']>;
  placeHasPrefix: InputMaybe<Scalars['String']['input']>;
  placeHasSuffix: InputMaybe<Scalars['String']['input']>;
  placeIn: InputMaybe<Array<Scalars['String']['input']>>;
  placeIsNil: InputMaybe<Scalars['Boolean']['input']>;
  placeLT: InputMaybe<Scalars['String']['input']>;
  placeLTE: InputMaybe<Scalars['String']['input']>;
  placeNEQ: InputMaybe<Scalars['String']['input']>;
  placeNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  placeNotNil: InputMaybe<Scalars['Boolean']['input']>;
  /** profile_pic_url field predicates */
  profilePicURL: InputMaybe<Scalars['String']['input']>;
  profilePicURLContains: InputMaybe<Scalars['String']['input']>;
  profilePicURLContainsFold: InputMaybe<Scalars['String']['input']>;
  profilePicURLEqualFold: InputMaybe<Scalars['String']['input']>;
  profilePicURLGT: InputMaybe<Scalars['String']['input']>;
  profilePicURLGTE: InputMaybe<Scalars['String']['input']>;
  profilePicURLHasPrefix: InputMaybe<Scalars['String']['input']>;
  profilePicURLHasSuffix: InputMaybe<Scalars['String']['input']>;
  profilePicURLIn: InputMaybe<Array<Scalars['String']['input']>>;
  profilePicURLIsNil: InputMaybe<Scalars['Boolean']['input']>;
  profilePicURLLT: InputMaybe<Scalars['String']['input']>;
  profilePicURLLTE: InputMaybe<Scalars['String']['input']>;
  profilePicURLNEQ: InputMaybe<Scalars['String']['input']>;
  profilePicURLNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  profilePicURLNotNil: InputMaybe<Scalars['Boolean']['input']>;
  /** role field predicates */
  role: InputMaybe<MemberRole>;
  roleIn: InputMaybe<Array<MemberRole>>;
  roleNEQ: InputMaybe<MemberRole>;
  roleNotIn: InputMaybe<Array<MemberRole>>;
  /** street field predicates */
  street: InputMaybe<Scalars['String']['input']>;
  streetContains: InputMaybe<Scalars['String']['input']>;
  streetContainsFold: InputMaybe<Scalars['String']['input']>;
  streetEqualFold: InputMaybe<Scalars['String']['input']>;
  streetGT: InputMaybe<Scalars['String']['input']>;
  streetGTE: InputMaybe<Scalars['String']['input']>;
  streetHasPrefix: InputMaybe<Scalars['String']['input']>;
  streetHasSuffix: InputMaybe<Scalars['String']['input']>;
  streetIn: InputMaybe<Array<Scalars['String']['input']>>;
  streetIsNil: InputMaybe<Scalars['Boolean']['input']>;
  streetLT: InputMaybe<Scalars['String']['input']>;
  streetLTE: InputMaybe<Scalars['String']['input']>;
  streetNEQ: InputMaybe<Scalars['String']['input']>;
  streetNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  streetNotNil: InputMaybe<Scalars['Boolean']['input']>;
  /** updated_at field predicates */
  updatedAt: InputMaybe<Scalars['Time']['input']>;
  updatedAtGT: InputMaybe<Scalars['Time']['input']>;
  updatedAtGTE: InputMaybe<Scalars['Time']['input']>;
  updatedAtIn: InputMaybe<Array<Scalars['Time']['input']>>;
  updatedAtLT: InputMaybe<Scalars['Time']['input']>;
  updatedAtLTE: InputMaybe<Scalars['Time']['input']>;
  updatedAtNEQ: InputMaybe<Scalars['Time']['input']>;
  updatedAtNotIn: InputMaybe<Array<Scalars['Time']['input']>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  CartProductCreate: CartProduct;
  CartProductCreateBulk: Maybe<Array<CartProduct>>;
  CartProductDelete: CartProduct;
  CartProductUpdate: CartProduct;
  CouponCreate: Coupon;
  CouponCreateBulk: Maybe<Array<Coupon>>;
  CouponDelete: Coupon;
  CouponUpdate: Coupon;
  DeleteFile: Scalars['Boolean']['output'];
  MemberCreate: Member;
  MemberCreateBulk: Maybe<Array<Member>>;
  MemberDelete: Member;
  MemberUpdate: Member;
  OrderCreate: Order;
  OrderCreateBulk: Maybe<Array<Order>>;
  OrderDelete: Order;
  OrderUpdate: Order;
  OrderedProductCreate: OrderedProduct;
  OrderedProductCreateBulk: Maybe<Array<OrderedProduct>>;
  OrderedProductDelete: OrderedProduct;
  OrderedProductUpdate: OrderedProduct;
  ProductCreate: Product;
  ProductCreateBulk: Maybe<Array<Product>>;
  ProductDelete: Product;
  ProductImagesCreate: ProductImages;
  ProductImagesCreateBulk: Maybe<Array<ProductImages>>;
  ProductImagesDelete: ProductImages;
  ProductImagesUpdate: ProductImages;
  ProductUpdate: Product;
  ProductVariantsCreate: ProductVariants;
  ProductVariantsCreateBulk: Maybe<Array<ProductVariants>>;
  ProductVariantsDelete: ProductVariants;
  ProductVariantsUpdate: ProductVariants;
  ping: Ping;
  userLogin: LoginResponse;
};


export type MutationCartProductCreateArgs = {
  input: CreateCartProductInput;
};


export type MutationCartProductCreateBulkArgs = {
  inputs: Array<InputMaybe<CreateCartProductInput>>;
};


export type MutationCartProductDeleteArgs = {
  id: Scalars['ID']['input'];
};


export type MutationCartProductUpdateArgs = {
  id: Scalars['ID']['input'];
  input: UpdateCartProductInput;
};


export type MutationCouponCreateArgs = {
  input: CreateCouponInput;
};


export type MutationCouponCreateBulkArgs = {
  inputs: Array<InputMaybe<CreateCouponInput>>;
};


export type MutationCouponDeleteArgs = {
  id: Scalars['ID']['input'];
};


export type MutationCouponUpdateArgs = {
  id: Scalars['ID']['input'];
  input: UpdateCouponInput;
};


export type MutationDeleteFileArgs = {
  event_id: Scalars['ID']['input'];
  url: Scalars['String']['input'];
};


export type MutationMemberCreateArgs = {
  input: CreateMemberInput;
};


export type MutationMemberCreateBulkArgs = {
  inputs: Array<InputMaybe<CreateMemberInput>>;
};


export type MutationMemberDeleteArgs = {
  id: Scalars['ID']['input'];
};


export type MutationMemberUpdateArgs = {
  id: Scalars['ID']['input'];
  input: UpdateMemberInput;
};


export type MutationOrderCreateArgs = {
  input: CreateOrderInput;
};


export type MutationOrderCreateBulkArgs = {
  inputs: Array<InputMaybe<CreateOrderInput>>;
};


export type MutationOrderDeleteArgs = {
  id: Scalars['ID']['input'];
};


export type MutationOrderUpdateArgs = {
  id: Scalars['ID']['input'];
  input: UpdateOrderInput;
};


export type MutationOrderedProductCreateArgs = {
  input: CreateOrderedProductInput;
};


export type MutationOrderedProductCreateBulkArgs = {
  inputs: Array<InputMaybe<CreateOrderedProductInput>>;
};


export type MutationOrderedProductDeleteArgs = {
  id: Scalars['ID']['input'];
};


export type MutationOrderedProductUpdateArgs = {
  id: Scalars['ID']['input'];
  input: UpdateOrderedProductInput;
};


export type MutationProductCreateArgs = {
  input: CreateProductInput;
};


export type MutationProductCreateBulkArgs = {
  inputs: Array<InputMaybe<CreateProductInput>>;
};


export type MutationProductDeleteArgs = {
  id: Scalars['ID']['input'];
};


export type MutationProductImagesCreateArgs = {
  input: CreateProductImagesInput;
};


export type MutationProductImagesCreateBulkArgs = {
  inputs: Array<InputMaybe<CreateProductImagesInput>>;
};


export type MutationProductImagesDeleteArgs = {
  id: Scalars['ID']['input'];
};


export type MutationProductImagesUpdateArgs = {
  id: Scalars['ID']['input'];
  input: UpdateProductImagesInput;
};


export type MutationProductUpdateArgs = {
  id: Scalars['ID']['input'];
  input: UpdateProductInput;
};


export type MutationProductVariantsCreateArgs = {
  input: CreateProductVariantsInput;
};


export type MutationProductVariantsCreateBulkArgs = {
  inputs: Array<InputMaybe<CreateProductVariantsInput>>;
};


export type MutationProductVariantsDeleteArgs = {
  id: Scalars['ID']['input'];
};


export type MutationProductVariantsUpdateArgs = {
  id: Scalars['ID']['input'];
  input: UpdateProductVariantsInput;
};


export type MutationUserLoginArgs = {
  firebaseToken: Scalars['String']['input'];
};

/**
 * An object with an ID.
 * Follows the [Relay Global Object Identification Specification](https://relay.dev/graphql/objectidentification.htm)
 */
export type Node = {
  /** The id of the object. */
  id: Scalars['ID']['output'];
};

export type Order = Node & {
  __typename?: 'Order';
  alternatePhoneNumber: Maybe<Scalars['String']['output']>;
  city: Maybe<Scalars['String']['output']>;
  createdAt: Scalars['Time']['output'];
  email: Scalars['String']['output'];
  houseNo: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  landmark: Maybe<Scalars['String']['output']>;
  orderDate: Scalars['Time']['output'];
  orderedProducts: Maybe<Array<OrderedProduct>>;
  paidAmount: Scalars['Float']['output'];
  phoneNumber: Maybe<Scalars['String']['output']>;
  pincode: Maybe<Scalars['String']['output']>;
  place: Maybe<Scalars['String']['output']>;
  street: Maybe<Scalars['String']['output']>;
  updatedAt: Scalars['Time']['output'];
  user: Member;
  userID: Scalars['ID']['output'];
};

/** A connection to a list of items. */
export type OrderConnection = {
  __typename?: 'OrderConnection';
  /** A list of edges. */
  edges: Maybe<Array<Maybe<OrderEdge>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  /** Identifies the total count of items in the connection. */
  totalCount: Scalars['Int']['output'];
};

/** Possible directions in which to order a list of items when provided an `orderBy` argument. */
export enum OrderDirection {
  /** Specifies an ascending order for a given `orderBy` argument. */
  Asc = 'ASC',
  /** Specifies a descending order for a given `orderBy` argument. */
  Desc = 'DESC'
}

/** An edge in a connection. */
export type OrderEdge = {
  __typename?: 'OrderEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['Cursor']['output'];
  /** The item at the end of the edge. */
  node: Maybe<Order>;
};

export enum OrderField {
  AlternatePhoneNumber = 'alternatePhoneNumber',
  City = 'city',
  CreatedAt = 'createdAt',
  Email = 'email',
  HouseNo = 'houseNo',
  Landmark = 'landmark',
  OrderDate = 'orderDate',
  PaidAmount = 'paidAmount',
  PhoneNumber = 'phoneNumber',
  Pincode = 'pincode',
  Place = 'place',
  Street = 'street',
  UpdatedAt = 'updatedAt',
  UserId = 'userID'
}

/** Ordering options for Order connections */
export type OrderOrder = {
  /** The ordering direction. */
  direction: OrderDirection;
  /** The field by which to order Orders. */
  field: OrderOrderField;
};

/** Properties by which Order connections can be ordered. */
export enum OrderOrderField {
  CreatedAt = 'createdAt',
  Id = 'id',
  UpdatedAt = 'updatedAt'
}

/**
 * OrderWhereInput is used for filtering Order objects.
 * Input was generated by ent.
 */
export type OrderWhereInput = {
  /** alternate_phone_number field predicates */
  alternatePhoneNumber: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberContains: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberContainsFold: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberEqualFold: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberGT: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberGTE: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberHasPrefix: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberHasSuffix: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberIn: InputMaybe<Array<Scalars['String']['input']>>;
  alternatePhoneNumberIsNil: InputMaybe<Scalars['Boolean']['input']>;
  alternatePhoneNumberLT: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberLTE: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberNEQ: InputMaybe<Scalars['String']['input']>;
  alternatePhoneNumberNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  alternatePhoneNumberNotNil: InputMaybe<Scalars['Boolean']['input']>;
  and: InputMaybe<Array<OrderWhereInput>>;
  /** city field predicates */
  city: InputMaybe<Scalars['String']['input']>;
  cityContains: InputMaybe<Scalars['String']['input']>;
  cityContainsFold: InputMaybe<Scalars['String']['input']>;
  cityEqualFold: InputMaybe<Scalars['String']['input']>;
  cityGT: InputMaybe<Scalars['String']['input']>;
  cityGTE: InputMaybe<Scalars['String']['input']>;
  cityHasPrefix: InputMaybe<Scalars['String']['input']>;
  cityHasSuffix: InputMaybe<Scalars['String']['input']>;
  cityIn: InputMaybe<Array<Scalars['String']['input']>>;
  cityIsNil: InputMaybe<Scalars['Boolean']['input']>;
  cityLT: InputMaybe<Scalars['String']['input']>;
  cityLTE: InputMaybe<Scalars['String']['input']>;
  cityNEQ: InputMaybe<Scalars['String']['input']>;
  cityNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  cityNotNil: InputMaybe<Scalars['Boolean']['input']>;
  /** created_at field predicates */
  createdAt: InputMaybe<Scalars['Time']['input']>;
  createdAtGT: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE: InputMaybe<Scalars['Time']['input']>;
  createdAtIn: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtLT: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn: InputMaybe<Array<Scalars['Time']['input']>>;
  /** email field predicates */
  email: InputMaybe<Scalars['String']['input']>;
  emailContains: InputMaybe<Scalars['String']['input']>;
  emailContainsFold: InputMaybe<Scalars['String']['input']>;
  emailEqualFold: InputMaybe<Scalars['String']['input']>;
  emailGT: InputMaybe<Scalars['String']['input']>;
  emailGTE: InputMaybe<Scalars['String']['input']>;
  emailHasPrefix: InputMaybe<Scalars['String']['input']>;
  emailHasSuffix: InputMaybe<Scalars['String']['input']>;
  emailIn: InputMaybe<Array<Scalars['String']['input']>>;
  emailLT: InputMaybe<Scalars['String']['input']>;
  emailLTE: InputMaybe<Scalars['String']['input']>;
  emailNEQ: InputMaybe<Scalars['String']['input']>;
  emailNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  /** ordered_products edge predicates */
  hasOrderedProducts: InputMaybe<Scalars['Boolean']['input']>;
  hasOrderedProductsWith: InputMaybe<Array<OrderedProductWhereInput>>;
  /** user edge predicates */
  hasUser: InputMaybe<Scalars['Boolean']['input']>;
  hasUserWith: InputMaybe<Array<MemberWhereInput>>;
  /** house_no field predicates */
  houseNo: InputMaybe<Scalars['String']['input']>;
  houseNoContains: InputMaybe<Scalars['String']['input']>;
  houseNoContainsFold: InputMaybe<Scalars['String']['input']>;
  houseNoEqualFold: InputMaybe<Scalars['String']['input']>;
  houseNoGT: InputMaybe<Scalars['String']['input']>;
  houseNoGTE: InputMaybe<Scalars['String']['input']>;
  houseNoHasPrefix: InputMaybe<Scalars['String']['input']>;
  houseNoHasSuffix: InputMaybe<Scalars['String']['input']>;
  houseNoIn: InputMaybe<Array<Scalars['String']['input']>>;
  houseNoIsNil: InputMaybe<Scalars['Boolean']['input']>;
  houseNoLT: InputMaybe<Scalars['String']['input']>;
  houseNoLTE: InputMaybe<Scalars['String']['input']>;
  houseNoNEQ: InputMaybe<Scalars['String']['input']>;
  houseNoNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  houseNoNotNil: InputMaybe<Scalars['Boolean']['input']>;
  /** id field predicates */
  id: InputMaybe<Scalars['ID']['input']>;
  idGT: InputMaybe<Scalars['ID']['input']>;
  idGTE: InputMaybe<Scalars['ID']['input']>;
  idIn: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT: InputMaybe<Scalars['ID']['input']>;
  idLTE: InputMaybe<Scalars['ID']['input']>;
  idNEQ: InputMaybe<Scalars['ID']['input']>;
  idNotIn: InputMaybe<Array<Scalars['ID']['input']>>;
  /** landmark field predicates */
  landmark: InputMaybe<Scalars['String']['input']>;
  landmarkContains: InputMaybe<Scalars['String']['input']>;
  landmarkContainsFold: InputMaybe<Scalars['String']['input']>;
  landmarkEqualFold: InputMaybe<Scalars['String']['input']>;
  landmarkGT: InputMaybe<Scalars['String']['input']>;
  landmarkGTE: InputMaybe<Scalars['String']['input']>;
  landmarkHasPrefix: InputMaybe<Scalars['String']['input']>;
  landmarkHasSuffix: InputMaybe<Scalars['String']['input']>;
  landmarkIn: InputMaybe<Array<Scalars['String']['input']>>;
  landmarkIsNil: InputMaybe<Scalars['Boolean']['input']>;
  landmarkLT: InputMaybe<Scalars['String']['input']>;
  landmarkLTE: InputMaybe<Scalars['String']['input']>;
  landmarkNEQ: InputMaybe<Scalars['String']['input']>;
  landmarkNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  landmarkNotNil: InputMaybe<Scalars['Boolean']['input']>;
  not: InputMaybe<OrderWhereInput>;
  or: InputMaybe<Array<OrderWhereInput>>;
  /** order_date field predicates */
  orderDate: InputMaybe<Scalars['Time']['input']>;
  orderDateGT: InputMaybe<Scalars['Time']['input']>;
  orderDateGTE: InputMaybe<Scalars['Time']['input']>;
  orderDateIn: InputMaybe<Array<Scalars['Time']['input']>>;
  orderDateLT: InputMaybe<Scalars['Time']['input']>;
  orderDateLTE: InputMaybe<Scalars['Time']['input']>;
  orderDateNEQ: InputMaybe<Scalars['Time']['input']>;
  orderDateNotIn: InputMaybe<Array<Scalars['Time']['input']>>;
  /** paid_amount field predicates */
  paidAmount: InputMaybe<Scalars['Float']['input']>;
  paidAmountGT: InputMaybe<Scalars['Float']['input']>;
  paidAmountGTE: InputMaybe<Scalars['Float']['input']>;
  paidAmountIn: InputMaybe<Array<Scalars['Float']['input']>>;
  paidAmountLT: InputMaybe<Scalars['Float']['input']>;
  paidAmountLTE: InputMaybe<Scalars['Float']['input']>;
  paidAmountNEQ: InputMaybe<Scalars['Float']['input']>;
  paidAmountNotIn: InputMaybe<Array<Scalars['Float']['input']>>;
  /** phone_number field predicates */
  phoneNumber: InputMaybe<Scalars['String']['input']>;
  phoneNumberContains: InputMaybe<Scalars['String']['input']>;
  phoneNumberContainsFold: InputMaybe<Scalars['String']['input']>;
  phoneNumberEqualFold: InputMaybe<Scalars['String']['input']>;
  phoneNumberGT: InputMaybe<Scalars['String']['input']>;
  phoneNumberGTE: InputMaybe<Scalars['String']['input']>;
  phoneNumberHasPrefix: InputMaybe<Scalars['String']['input']>;
  phoneNumberHasSuffix: InputMaybe<Scalars['String']['input']>;
  phoneNumberIn: InputMaybe<Array<Scalars['String']['input']>>;
  phoneNumberIsNil: InputMaybe<Scalars['Boolean']['input']>;
  phoneNumberLT: InputMaybe<Scalars['String']['input']>;
  phoneNumberLTE: InputMaybe<Scalars['String']['input']>;
  phoneNumberNEQ: InputMaybe<Scalars['String']['input']>;
  phoneNumberNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  phoneNumberNotNil: InputMaybe<Scalars['Boolean']['input']>;
  /** pincode field predicates */
  pincode: InputMaybe<Scalars['String']['input']>;
  pincodeContains: InputMaybe<Scalars['String']['input']>;
  pincodeContainsFold: InputMaybe<Scalars['String']['input']>;
  pincodeEqualFold: InputMaybe<Scalars['String']['input']>;
  pincodeGT: InputMaybe<Scalars['String']['input']>;
  pincodeGTE: InputMaybe<Scalars['String']['input']>;
  pincodeHasPrefix: InputMaybe<Scalars['String']['input']>;
  pincodeHasSuffix: InputMaybe<Scalars['String']['input']>;
  pincodeIn: InputMaybe<Array<Scalars['String']['input']>>;
  pincodeIsNil: InputMaybe<Scalars['Boolean']['input']>;
  pincodeLT: InputMaybe<Scalars['String']['input']>;
  pincodeLTE: InputMaybe<Scalars['String']['input']>;
  pincodeNEQ: InputMaybe<Scalars['String']['input']>;
  pincodeNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  pincodeNotNil: InputMaybe<Scalars['Boolean']['input']>;
  /** place field predicates */
  place: InputMaybe<Scalars['String']['input']>;
  placeContains: InputMaybe<Scalars['String']['input']>;
  placeContainsFold: InputMaybe<Scalars['String']['input']>;
  placeEqualFold: InputMaybe<Scalars['String']['input']>;
  placeGT: InputMaybe<Scalars['String']['input']>;
  placeGTE: InputMaybe<Scalars['String']['input']>;
  placeHasPrefix: InputMaybe<Scalars['String']['input']>;
  placeHasSuffix: InputMaybe<Scalars['String']['input']>;
  placeIn: InputMaybe<Array<Scalars['String']['input']>>;
  placeIsNil: InputMaybe<Scalars['Boolean']['input']>;
  placeLT: InputMaybe<Scalars['String']['input']>;
  placeLTE: InputMaybe<Scalars['String']['input']>;
  placeNEQ: InputMaybe<Scalars['String']['input']>;
  placeNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  placeNotNil: InputMaybe<Scalars['Boolean']['input']>;
  /** street field predicates */
  street: InputMaybe<Scalars['String']['input']>;
  streetContains: InputMaybe<Scalars['String']['input']>;
  streetContainsFold: InputMaybe<Scalars['String']['input']>;
  streetEqualFold: InputMaybe<Scalars['String']['input']>;
  streetGT: InputMaybe<Scalars['String']['input']>;
  streetGTE: InputMaybe<Scalars['String']['input']>;
  streetHasPrefix: InputMaybe<Scalars['String']['input']>;
  streetHasSuffix: InputMaybe<Scalars['String']['input']>;
  streetIn: InputMaybe<Array<Scalars['String']['input']>>;
  streetIsNil: InputMaybe<Scalars['Boolean']['input']>;
  streetLT: InputMaybe<Scalars['String']['input']>;
  streetLTE: InputMaybe<Scalars['String']['input']>;
  streetNEQ: InputMaybe<Scalars['String']['input']>;
  streetNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  streetNotNil: InputMaybe<Scalars['Boolean']['input']>;
  /** updated_at field predicates */
  updatedAt: InputMaybe<Scalars['Time']['input']>;
  updatedAtGT: InputMaybe<Scalars['Time']['input']>;
  updatedAtGTE: InputMaybe<Scalars['Time']['input']>;
  updatedAtIn: InputMaybe<Array<Scalars['Time']['input']>>;
  updatedAtLT: InputMaybe<Scalars['Time']['input']>;
  updatedAtLTE: InputMaybe<Scalars['Time']['input']>;
  updatedAtNEQ: InputMaybe<Scalars['Time']['input']>;
  updatedAtNotIn: InputMaybe<Array<Scalars['Time']['input']>>;
  /** user_id field predicates */
  userID: InputMaybe<Scalars['ID']['input']>;
  userIDIn: InputMaybe<Array<Scalars['ID']['input']>>;
  userIDNEQ: InputMaybe<Scalars['ID']['input']>;
  userIDNotIn: InputMaybe<Array<Scalars['ID']['input']>>;
};

export type OrderedProduct = Node & {
  __typename?: 'OrderedProduct';
  createdAt: Scalars['Time']['output'];
  id: Scalars['ID']['output'];
  order: Order;
  orderID: Scalars['ID']['output'];
  product: Product;
  productID: Scalars['ID']['output'];
  quantity: Scalars['Int']['output'];
  status: Scalars['String']['output'];
  toDeliver: Scalars['Boolean']['output'];
  updatedAt: Scalars['Time']['output'];
  user: Member;
  userID: Scalars['ID']['output'];
  variant: Scalars['String']['output'];
};

/** A connection to a list of items. */
export type OrderedProductConnection = {
  __typename?: 'OrderedProductConnection';
  /** A list of edges. */
  edges: Maybe<Array<Maybe<OrderedProductEdge>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  /** Identifies the total count of items in the connection. */
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type OrderedProductEdge = {
  __typename?: 'OrderedProductEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['Cursor']['output'];
  /** The item at the end of the edge. */
  node: Maybe<OrderedProduct>;
};

export enum OrderedProductField {
  CreatedAt = 'createdAt',
  OrderId = 'orderID',
  ProductId = 'productID',
  Quantity = 'quantity',
  Status = 'status',
  ToDeliver = 'toDeliver',
  UpdatedAt = 'updatedAt',
  UserId = 'userID',
  Variant = 'variant'
}

/** Ordering options for OrderedProduct connections */
export type OrderedProductOrder = {
  /** The ordering direction. */
  direction: OrderDirection;
  /** The field by which to order OrderedProducts. */
  field: OrderedProductOrderField;
};

/** Properties by which OrderedProduct connections can be ordered. */
export enum OrderedProductOrderField {
  CreatedAt = 'createdAt',
  Id = 'id',
  UpdatedAt = 'updatedAt'
}

/**
 * OrderedProductWhereInput is used for filtering OrderedProduct objects.
 * Input was generated by ent.
 */
export type OrderedProductWhereInput = {
  and: InputMaybe<Array<OrderedProductWhereInput>>;
  /** created_at field predicates */
  createdAt: InputMaybe<Scalars['Time']['input']>;
  createdAtGT: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE: InputMaybe<Scalars['Time']['input']>;
  createdAtIn: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtLT: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn: InputMaybe<Array<Scalars['Time']['input']>>;
  /** order edge predicates */
  hasOrder: InputMaybe<Scalars['Boolean']['input']>;
  hasOrderWith: InputMaybe<Array<OrderWhereInput>>;
  /** product edge predicates */
  hasProduct: InputMaybe<Scalars['Boolean']['input']>;
  hasProductWith: InputMaybe<Array<ProductWhereInput>>;
  /** user edge predicates */
  hasUser: InputMaybe<Scalars['Boolean']['input']>;
  hasUserWith: InputMaybe<Array<MemberWhereInput>>;
  /** id field predicates */
  id: InputMaybe<Scalars['ID']['input']>;
  idGT: InputMaybe<Scalars['ID']['input']>;
  idGTE: InputMaybe<Scalars['ID']['input']>;
  idIn: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT: InputMaybe<Scalars['ID']['input']>;
  idLTE: InputMaybe<Scalars['ID']['input']>;
  idNEQ: InputMaybe<Scalars['ID']['input']>;
  idNotIn: InputMaybe<Array<Scalars['ID']['input']>>;
  not: InputMaybe<OrderedProductWhereInput>;
  or: InputMaybe<Array<OrderedProductWhereInput>>;
  /** order_id field predicates */
  orderID: InputMaybe<Scalars['ID']['input']>;
  orderIDIn: InputMaybe<Array<Scalars['ID']['input']>>;
  orderIDNEQ: InputMaybe<Scalars['ID']['input']>;
  orderIDNotIn: InputMaybe<Array<Scalars['ID']['input']>>;
  /** product_id field predicates */
  productID: InputMaybe<Scalars['ID']['input']>;
  productIDIn: InputMaybe<Array<Scalars['ID']['input']>>;
  productIDNEQ: InputMaybe<Scalars['ID']['input']>;
  productIDNotIn: InputMaybe<Array<Scalars['ID']['input']>>;
  /** quantity field predicates */
  quantity: InputMaybe<Scalars['Int']['input']>;
  quantityGT: InputMaybe<Scalars['Int']['input']>;
  quantityGTE: InputMaybe<Scalars['Int']['input']>;
  quantityIn: InputMaybe<Array<Scalars['Int']['input']>>;
  quantityLT: InputMaybe<Scalars['Int']['input']>;
  quantityLTE: InputMaybe<Scalars['Int']['input']>;
  quantityNEQ: InputMaybe<Scalars['Int']['input']>;
  quantityNotIn: InputMaybe<Array<Scalars['Int']['input']>>;
  /** status field predicates */
  status: InputMaybe<Scalars['String']['input']>;
  statusContains: InputMaybe<Scalars['String']['input']>;
  statusContainsFold: InputMaybe<Scalars['String']['input']>;
  statusEqualFold: InputMaybe<Scalars['String']['input']>;
  statusGT: InputMaybe<Scalars['String']['input']>;
  statusGTE: InputMaybe<Scalars['String']['input']>;
  statusHasPrefix: InputMaybe<Scalars['String']['input']>;
  statusHasSuffix: InputMaybe<Scalars['String']['input']>;
  statusIn: InputMaybe<Array<Scalars['String']['input']>>;
  statusLT: InputMaybe<Scalars['String']['input']>;
  statusLTE: InputMaybe<Scalars['String']['input']>;
  statusNEQ: InputMaybe<Scalars['String']['input']>;
  statusNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  /** to_deliver field predicates */
  toDeliver: InputMaybe<Scalars['Boolean']['input']>;
  toDeliverNEQ: InputMaybe<Scalars['Boolean']['input']>;
  /** updated_at field predicates */
  updatedAt: InputMaybe<Scalars['Time']['input']>;
  updatedAtGT: InputMaybe<Scalars['Time']['input']>;
  updatedAtGTE: InputMaybe<Scalars['Time']['input']>;
  updatedAtIn: InputMaybe<Array<Scalars['Time']['input']>>;
  updatedAtLT: InputMaybe<Scalars['Time']['input']>;
  updatedAtLTE: InputMaybe<Scalars['Time']['input']>;
  updatedAtNEQ: InputMaybe<Scalars['Time']['input']>;
  updatedAtNotIn: InputMaybe<Array<Scalars['Time']['input']>>;
  /** user_id field predicates */
  userID: InputMaybe<Scalars['ID']['input']>;
  userIDIn: InputMaybe<Array<Scalars['ID']['input']>>;
  userIDNEQ: InputMaybe<Scalars['ID']['input']>;
  userIDNotIn: InputMaybe<Array<Scalars['ID']['input']>>;
  /** variant field predicates */
  variant: InputMaybe<Scalars['String']['input']>;
  variantContains: InputMaybe<Scalars['String']['input']>;
  variantContainsFold: InputMaybe<Scalars['String']['input']>;
  variantEqualFold: InputMaybe<Scalars['String']['input']>;
  variantGT: InputMaybe<Scalars['String']['input']>;
  variantGTE: InputMaybe<Scalars['String']['input']>;
  variantHasPrefix: InputMaybe<Scalars['String']['input']>;
  variantHasSuffix: InputMaybe<Scalars['String']['input']>;
  variantIn: InputMaybe<Array<Scalars['String']['input']>>;
  variantLT: InputMaybe<Scalars['String']['input']>;
  variantLTE: InputMaybe<Scalars['String']['input']>;
  variantNEQ: InputMaybe<Scalars['String']['input']>;
  variantNotIn: InputMaybe<Array<Scalars['String']['input']>>;
};

/**
 * Information about pagination in a connection.
 * https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo
 */
export type PageInfo = {
  __typename?: 'PageInfo';
  /** When paginating forwards, the cursor to continue. */
  endCursor: Maybe<Scalars['Cursor']['output']>;
  /** When paginating forwards, are there more items? */
  hasNextPage: Scalars['Boolean']['output'];
  /** When paginating backwards, are there more items? */
  hasPreviousPage: Scalars['Boolean']['output'];
  /** When paginating backwards, the cursor to continue. */
  startCursor: Maybe<Scalars['Cursor']['output']>;
};

export type Ping = {
  __typename?: 'Ping';
  success: Scalars['Boolean']['output'];
};

export type Product = Node & {
  __typename?: 'Product';
  category: ProductCategory;
  createdAt: Scalars['Time']['output'];
  description: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  images: Maybe<Array<ProductImages>>;
  inCartProducts: Maybe<Array<CartProduct>>;
  isDeliverable: Scalars['Boolean']['output'];
  name: Scalars['String']['output'];
  orderedProducts: Maybe<Array<OrderedProduct>>;
  price: Scalars['String']['output'];
  updatedAt: Scalars['Time']['output'];
  variants: Maybe<Array<ProductVariants>>;
  weight: Scalars['Int']['output'];
};

/** ProductCategory is enum for the field category */
export enum ProductCategory {
  ExperienceStore = 'experience_store',
  Merchandise = 'merchandise'
}

/** A connection to a list of items. */
export type ProductConnection = {
  __typename?: 'ProductConnection';
  /** A list of edges. */
  edges: Maybe<Array<Maybe<ProductEdge>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  /** Identifies the total count of items in the connection. */
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type ProductEdge = {
  __typename?: 'ProductEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['Cursor']['output'];
  /** The item at the end of the edge. */
  node: Maybe<Product>;
};

export enum ProductField {
  Category = 'category',
  CreatedAt = 'createdAt',
  Description = 'description',
  IsDeliverable = 'isDeliverable',
  Name = 'name',
  Price = 'price',
  UpdatedAt = 'updatedAt',
  Weight = 'weight'
}

export type ProductImages = Node & {
  __typename?: 'ProductImages';
  createdAt: Scalars['Time']['output'];
  id: Scalars['ID']['output'];
  imageURL: Scalars['String']['output'];
  product: Product;
  productID: Scalars['ID']['output'];
  updatedAt: Scalars['Time']['output'];
};

/** A connection to a list of items. */
export type ProductImagesConnection = {
  __typename?: 'ProductImagesConnection';
  /** A list of edges. */
  edges: Maybe<Array<Maybe<ProductImagesEdge>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  /** Identifies the total count of items in the connection. */
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type ProductImagesEdge = {
  __typename?: 'ProductImagesEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['Cursor']['output'];
  /** The item at the end of the edge. */
  node: Maybe<ProductImages>;
};

export enum ProductImagesField {
  CreatedAt = 'createdAt',
  ImageUrl = 'imageURL',
  ProductId = 'productID',
  UpdatedAt = 'updatedAt'
}

/** Ordering options for ProductImages connections */
export type ProductImagesOrder = {
  /** The ordering direction. */
  direction: OrderDirection;
  /** The field by which to order ProductImagesSlice. */
  field: ProductImagesOrderField;
};

/** Properties by which ProductImages connections can be ordered. */
export enum ProductImagesOrderField {
  CreatedAt = 'createdAt',
  Id = 'id',
  UpdatedAt = 'updatedAt'
}

/**
 * ProductImagesWhereInput is used for filtering ProductImages objects.
 * Input was generated by ent.
 */
export type ProductImagesWhereInput = {
  and: InputMaybe<Array<ProductImagesWhereInput>>;
  /** created_at field predicates */
  createdAt: InputMaybe<Scalars['Time']['input']>;
  createdAtGT: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE: InputMaybe<Scalars['Time']['input']>;
  createdAtIn: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtLT: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn: InputMaybe<Array<Scalars['Time']['input']>>;
  /** product edge predicates */
  hasProduct: InputMaybe<Scalars['Boolean']['input']>;
  hasProductWith: InputMaybe<Array<ProductWhereInput>>;
  /** id field predicates */
  id: InputMaybe<Scalars['ID']['input']>;
  idGT: InputMaybe<Scalars['ID']['input']>;
  idGTE: InputMaybe<Scalars['ID']['input']>;
  idIn: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT: InputMaybe<Scalars['ID']['input']>;
  idLTE: InputMaybe<Scalars['ID']['input']>;
  idNEQ: InputMaybe<Scalars['ID']['input']>;
  idNotIn: InputMaybe<Array<Scalars['ID']['input']>>;
  /** image_url field predicates */
  imageURL: InputMaybe<Scalars['String']['input']>;
  imageURLContains: InputMaybe<Scalars['String']['input']>;
  imageURLContainsFold: InputMaybe<Scalars['String']['input']>;
  imageURLEqualFold: InputMaybe<Scalars['String']['input']>;
  imageURLGT: InputMaybe<Scalars['String']['input']>;
  imageURLGTE: InputMaybe<Scalars['String']['input']>;
  imageURLHasPrefix: InputMaybe<Scalars['String']['input']>;
  imageURLHasSuffix: InputMaybe<Scalars['String']['input']>;
  imageURLIn: InputMaybe<Array<Scalars['String']['input']>>;
  imageURLLT: InputMaybe<Scalars['String']['input']>;
  imageURLLTE: InputMaybe<Scalars['String']['input']>;
  imageURLNEQ: InputMaybe<Scalars['String']['input']>;
  imageURLNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  not: InputMaybe<ProductImagesWhereInput>;
  or: InputMaybe<Array<ProductImagesWhereInput>>;
  /** product_id field predicates */
  productID: InputMaybe<Scalars['ID']['input']>;
  productIDIn: InputMaybe<Array<Scalars['ID']['input']>>;
  productIDNEQ: InputMaybe<Scalars['ID']['input']>;
  productIDNotIn: InputMaybe<Array<Scalars['ID']['input']>>;
  /** updated_at field predicates */
  updatedAt: InputMaybe<Scalars['Time']['input']>;
  updatedAtGT: InputMaybe<Scalars['Time']['input']>;
  updatedAtGTE: InputMaybe<Scalars['Time']['input']>;
  updatedAtIn: InputMaybe<Array<Scalars['Time']['input']>>;
  updatedAtLT: InputMaybe<Scalars['Time']['input']>;
  updatedAtLTE: InputMaybe<Scalars['Time']['input']>;
  updatedAtNEQ: InputMaybe<Scalars['Time']['input']>;
  updatedAtNotIn: InputMaybe<Array<Scalars['Time']['input']>>;
};

/** Ordering options for Product connections */
export type ProductOrder = {
  /** The ordering direction. */
  direction: OrderDirection;
  /** The field by which to order Products. */
  field: ProductOrderField;
};

/** Properties by which Product connections can be ordered. */
export enum ProductOrderField {
  CreatedAt = 'createdAt',
  Id = 'id',
  Name = 'name',
  UpdatedAt = 'updatedAt'
}

export type ProductVariants = Node & {
  __typename?: 'ProductVariants';
  createdAt: Scalars['Time']['output'];
  id: Scalars['ID']['output'];
  product: Product;
  productID: Scalars['ID']['output'];
  quantity: Scalars['Int']['output'];
  updatedAt: Scalars['Time']['output'];
  variant: Scalars['String']['output'];
};

/** A connection to a list of items. */
export type ProductVariantsConnection = {
  __typename?: 'ProductVariantsConnection';
  /** A list of edges. */
  edges: Maybe<Array<Maybe<ProductVariantsEdge>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  /** Identifies the total count of items in the connection. */
  totalCount: Scalars['Int']['output'];
};

/** An edge in a connection. */
export type ProductVariantsEdge = {
  __typename?: 'ProductVariantsEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['Cursor']['output'];
  /** The item at the end of the edge. */
  node: Maybe<ProductVariants>;
};

export enum ProductVariantsField {
  CreatedAt = 'createdAt',
  ProductId = 'productID',
  Quantity = 'quantity',
  UpdatedAt = 'updatedAt',
  Variant = 'variant'
}

/** Ordering options for ProductVariants connections */
export type ProductVariantsOrder = {
  /** The ordering direction. */
  direction: OrderDirection;
  /** The field by which to order ProductVariantsSlice. */
  field: ProductVariantsOrderField;
};

/** Properties by which ProductVariants connections can be ordered. */
export enum ProductVariantsOrderField {
  CreatedAt = 'createdAt',
  Id = 'id',
  UpdatedAt = 'updatedAt'
}

/**
 * ProductVariantsWhereInput is used for filtering ProductVariants objects.
 * Input was generated by ent.
 */
export type ProductVariantsWhereInput = {
  and: InputMaybe<Array<ProductVariantsWhereInput>>;
  /** created_at field predicates */
  createdAt: InputMaybe<Scalars['Time']['input']>;
  createdAtGT: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE: InputMaybe<Scalars['Time']['input']>;
  createdAtIn: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtLT: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn: InputMaybe<Array<Scalars['Time']['input']>>;
  /** product edge predicates */
  hasProduct: InputMaybe<Scalars['Boolean']['input']>;
  hasProductWith: InputMaybe<Array<ProductWhereInput>>;
  /** id field predicates */
  id: InputMaybe<Scalars['ID']['input']>;
  idGT: InputMaybe<Scalars['ID']['input']>;
  idGTE: InputMaybe<Scalars['ID']['input']>;
  idIn: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT: InputMaybe<Scalars['ID']['input']>;
  idLTE: InputMaybe<Scalars['ID']['input']>;
  idNEQ: InputMaybe<Scalars['ID']['input']>;
  idNotIn: InputMaybe<Array<Scalars['ID']['input']>>;
  not: InputMaybe<ProductVariantsWhereInput>;
  or: InputMaybe<Array<ProductVariantsWhereInput>>;
  /** product_id field predicates */
  productID: InputMaybe<Scalars['ID']['input']>;
  productIDIn: InputMaybe<Array<Scalars['ID']['input']>>;
  productIDNEQ: InputMaybe<Scalars['ID']['input']>;
  productIDNotIn: InputMaybe<Array<Scalars['ID']['input']>>;
  /** quantity field predicates */
  quantity: InputMaybe<Scalars['Int']['input']>;
  quantityGT: InputMaybe<Scalars['Int']['input']>;
  quantityGTE: InputMaybe<Scalars['Int']['input']>;
  quantityIn: InputMaybe<Array<Scalars['Int']['input']>>;
  quantityLT: InputMaybe<Scalars['Int']['input']>;
  quantityLTE: InputMaybe<Scalars['Int']['input']>;
  quantityNEQ: InputMaybe<Scalars['Int']['input']>;
  quantityNotIn: InputMaybe<Array<Scalars['Int']['input']>>;
  /** updated_at field predicates */
  updatedAt: InputMaybe<Scalars['Time']['input']>;
  updatedAtGT: InputMaybe<Scalars['Time']['input']>;
  updatedAtGTE: InputMaybe<Scalars['Time']['input']>;
  updatedAtIn: InputMaybe<Array<Scalars['Time']['input']>>;
  updatedAtLT: InputMaybe<Scalars['Time']['input']>;
  updatedAtLTE: InputMaybe<Scalars['Time']['input']>;
  updatedAtNEQ: InputMaybe<Scalars['Time']['input']>;
  updatedAtNotIn: InputMaybe<Array<Scalars['Time']['input']>>;
  /** variant field predicates */
  variant: InputMaybe<Scalars['String']['input']>;
  variantContains: InputMaybe<Scalars['String']['input']>;
  variantContainsFold: InputMaybe<Scalars['String']['input']>;
  variantEqualFold: InputMaybe<Scalars['String']['input']>;
  variantGT: InputMaybe<Scalars['String']['input']>;
  variantGTE: InputMaybe<Scalars['String']['input']>;
  variantHasPrefix: InputMaybe<Scalars['String']['input']>;
  variantHasSuffix: InputMaybe<Scalars['String']['input']>;
  variantIn: InputMaybe<Array<Scalars['String']['input']>>;
  variantLT: InputMaybe<Scalars['String']['input']>;
  variantLTE: InputMaybe<Scalars['String']['input']>;
  variantNEQ: InputMaybe<Scalars['String']['input']>;
  variantNotIn: InputMaybe<Array<Scalars['String']['input']>>;
};

/**
 * ProductWhereInput is used for filtering Product objects.
 * Input was generated by ent.
 */
export type ProductWhereInput = {
  and: InputMaybe<Array<ProductWhereInput>>;
  /** category field predicates */
  category: InputMaybe<ProductCategory>;
  categoryIn: InputMaybe<Array<ProductCategory>>;
  categoryNEQ: InputMaybe<ProductCategory>;
  categoryNotIn: InputMaybe<Array<ProductCategory>>;
  /** created_at field predicates */
  createdAt: InputMaybe<Scalars['Time']['input']>;
  createdAtGT: InputMaybe<Scalars['Time']['input']>;
  createdAtGTE: InputMaybe<Scalars['Time']['input']>;
  createdAtIn: InputMaybe<Array<Scalars['Time']['input']>>;
  createdAtLT: InputMaybe<Scalars['Time']['input']>;
  createdAtLTE: InputMaybe<Scalars['Time']['input']>;
  createdAtNEQ: InputMaybe<Scalars['Time']['input']>;
  createdAtNotIn: InputMaybe<Array<Scalars['Time']['input']>>;
  /** description field predicates */
  description: InputMaybe<Scalars['String']['input']>;
  descriptionContains: InputMaybe<Scalars['String']['input']>;
  descriptionContainsFold: InputMaybe<Scalars['String']['input']>;
  descriptionEqualFold: InputMaybe<Scalars['String']['input']>;
  descriptionGT: InputMaybe<Scalars['String']['input']>;
  descriptionGTE: InputMaybe<Scalars['String']['input']>;
  descriptionHasPrefix: InputMaybe<Scalars['String']['input']>;
  descriptionHasSuffix: InputMaybe<Scalars['String']['input']>;
  descriptionIn: InputMaybe<Array<Scalars['String']['input']>>;
  descriptionIsNil: InputMaybe<Scalars['Boolean']['input']>;
  descriptionLT: InputMaybe<Scalars['String']['input']>;
  descriptionLTE: InputMaybe<Scalars['String']['input']>;
  descriptionNEQ: InputMaybe<Scalars['String']['input']>;
  descriptionNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  descriptionNotNil: InputMaybe<Scalars['Boolean']['input']>;
  /** images edge predicates */
  hasImages: InputMaybe<Scalars['Boolean']['input']>;
  hasImagesWith: InputMaybe<Array<ProductImagesWhereInput>>;
  /** in_cart_products edge predicates */
  hasInCartProducts: InputMaybe<Scalars['Boolean']['input']>;
  hasInCartProductsWith: InputMaybe<Array<CartProductWhereInput>>;
  /** ordered_products edge predicates */
  hasOrderedProducts: InputMaybe<Scalars['Boolean']['input']>;
  hasOrderedProductsWith: InputMaybe<Array<OrderedProductWhereInput>>;
  /** variants edge predicates */
  hasVariants: InputMaybe<Scalars['Boolean']['input']>;
  hasVariantsWith: InputMaybe<Array<ProductVariantsWhereInput>>;
  /** id field predicates */
  id: InputMaybe<Scalars['ID']['input']>;
  idGT: InputMaybe<Scalars['ID']['input']>;
  idGTE: InputMaybe<Scalars['ID']['input']>;
  idIn: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT: InputMaybe<Scalars['ID']['input']>;
  idLTE: InputMaybe<Scalars['ID']['input']>;
  idNEQ: InputMaybe<Scalars['ID']['input']>;
  idNotIn: InputMaybe<Array<Scalars['ID']['input']>>;
  /** is_deliverable field predicates */
  isDeliverable: InputMaybe<Scalars['Boolean']['input']>;
  isDeliverableNEQ: InputMaybe<Scalars['Boolean']['input']>;
  /** name field predicates */
  name: InputMaybe<Scalars['String']['input']>;
  nameContains: InputMaybe<Scalars['String']['input']>;
  nameContainsFold: InputMaybe<Scalars['String']['input']>;
  nameEqualFold: InputMaybe<Scalars['String']['input']>;
  nameGT: InputMaybe<Scalars['String']['input']>;
  nameGTE: InputMaybe<Scalars['String']['input']>;
  nameHasPrefix: InputMaybe<Scalars['String']['input']>;
  nameHasSuffix: InputMaybe<Scalars['String']['input']>;
  nameIn: InputMaybe<Array<Scalars['String']['input']>>;
  nameLT: InputMaybe<Scalars['String']['input']>;
  nameLTE: InputMaybe<Scalars['String']['input']>;
  nameNEQ: InputMaybe<Scalars['String']['input']>;
  nameNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  not: InputMaybe<ProductWhereInput>;
  or: InputMaybe<Array<ProductWhereInput>>;
  /** price field predicates */
  price: InputMaybe<Scalars['String']['input']>;
  priceContains: InputMaybe<Scalars['String']['input']>;
  priceContainsFold: InputMaybe<Scalars['String']['input']>;
  priceEqualFold: InputMaybe<Scalars['String']['input']>;
  priceGT: InputMaybe<Scalars['String']['input']>;
  priceGTE: InputMaybe<Scalars['String']['input']>;
  priceHasPrefix: InputMaybe<Scalars['String']['input']>;
  priceHasSuffix: InputMaybe<Scalars['String']['input']>;
  priceIn: InputMaybe<Array<Scalars['String']['input']>>;
  priceLT: InputMaybe<Scalars['String']['input']>;
  priceLTE: InputMaybe<Scalars['String']['input']>;
  priceNEQ: InputMaybe<Scalars['String']['input']>;
  priceNotIn: InputMaybe<Array<Scalars['String']['input']>>;
  /** updated_at field predicates */
  updatedAt: InputMaybe<Scalars['Time']['input']>;
  updatedAtGT: InputMaybe<Scalars['Time']['input']>;
  updatedAtGTE: InputMaybe<Scalars['Time']['input']>;
  updatedAtIn: InputMaybe<Array<Scalars['Time']['input']>>;
  updatedAtLT: InputMaybe<Scalars['Time']['input']>;
  updatedAtLTE: InputMaybe<Scalars['Time']['input']>;
  updatedAtNEQ: InputMaybe<Scalars['Time']['input']>;
  updatedAtNotIn: InputMaybe<Array<Scalars['Time']['input']>>;
  /** weight field predicates */
  weight: InputMaybe<Scalars['Int']['input']>;
  weightGT: InputMaybe<Scalars['Int']['input']>;
  weightGTE: InputMaybe<Scalars['Int']['input']>;
  weightIn: InputMaybe<Array<Scalars['Int']['input']>>;
  weightLT: InputMaybe<Scalars['Int']['input']>;
  weightLTE: InputMaybe<Scalars['Int']['input']>;
  weightNEQ: InputMaybe<Scalars['Int']['input']>;
  weightNotIn: InputMaybe<Array<Scalars['Int']['input']>>;
};

export type Query = {
  __typename?: 'Query';
  CartProductExport: Maybe<Scalars['String']['output']>;
  CartProductQuery: CartProductConnection;
  CouponExport: Maybe<Scalars['String']['output']>;
  CouponQuery: CouponConnection;
  MemberExport: Maybe<Scalars['String']['output']>;
  MemberQuery: MemberConnection;
  OrderExport: Maybe<Scalars['String']['output']>;
  OrderQuery: OrderConnection;
  OrderedProductExport: Maybe<Scalars['String']['output']>;
  OrderedProductQuery: OrderedProductConnection;
  ProductExport: Maybe<Scalars['String']['output']>;
  ProductImagesExport: Maybe<Scalars['String']['output']>;
  ProductImagesQuery: ProductImagesConnection;
  ProductQuery: ProductConnection;
  ProductVariantsExport: Maybe<Scalars['String']['output']>;
  ProductVariantsQuery: ProductVariantsConnection;
  /** Fetches an object given its ID. */
  node: Maybe<Node>;
  /** Lookup nodes by a list of IDs. */
  nodes: Array<Maybe<Node>>;
  ping: Ping;
  taskStatus: TaskState;
};


export type QueryCartProductExportArgs = {
  after: InputMaybe<Scalars['Cursor']['input']>;
  before: InputMaybe<Scalars['Cursor']['input']>;
  excelUrl: InputMaybe<Scalars['String']['input']>;
  fileType: Scalars['String']['input'];
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  orderBy: InputMaybe<Array<CartProductOrder>>;
  where: InputMaybe<CartProductWhereInput>;
};


export type QueryCartProductQueryArgs = {
  after: InputMaybe<Scalars['Cursor']['input']>;
  before: InputMaybe<Scalars['Cursor']['input']>;
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  orderBy: InputMaybe<Array<CartProductOrder>>;
  where: InputMaybe<CartProductWhereInput>;
};


export type QueryCouponExportArgs = {
  after: InputMaybe<Scalars['Cursor']['input']>;
  before: InputMaybe<Scalars['Cursor']['input']>;
  excelUrl: InputMaybe<Scalars['String']['input']>;
  fileType: Scalars['String']['input'];
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  orderBy: InputMaybe<Array<CouponOrder>>;
  where: InputMaybe<CouponWhereInput>;
};


export type QueryCouponQueryArgs = {
  after: InputMaybe<Scalars['Cursor']['input']>;
  before: InputMaybe<Scalars['Cursor']['input']>;
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  orderBy: InputMaybe<Array<CouponOrder>>;
  where: InputMaybe<CouponWhereInput>;
};


export type QueryMemberExportArgs = {
  after: InputMaybe<Scalars['Cursor']['input']>;
  before: InputMaybe<Scalars['Cursor']['input']>;
  excelUrl: InputMaybe<Scalars['String']['input']>;
  fileType: Scalars['String']['input'];
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  orderBy: InputMaybe<Array<MemberOrder>>;
  where: InputMaybe<MemberWhereInput>;
};


export type QueryMemberQueryArgs = {
  after: InputMaybe<Scalars['Cursor']['input']>;
  before: InputMaybe<Scalars['Cursor']['input']>;
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  orderBy: InputMaybe<Array<MemberOrder>>;
  where: InputMaybe<MemberWhereInput>;
};


export type QueryOrderExportArgs = {
  after: InputMaybe<Scalars['Cursor']['input']>;
  before: InputMaybe<Scalars['Cursor']['input']>;
  excelUrl: InputMaybe<Scalars['String']['input']>;
  fileType: Scalars['String']['input'];
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  orderBy: InputMaybe<Array<OrderOrder>>;
  where: InputMaybe<OrderWhereInput>;
};


export type QueryOrderQueryArgs = {
  after: InputMaybe<Scalars['Cursor']['input']>;
  before: InputMaybe<Scalars['Cursor']['input']>;
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  orderBy: InputMaybe<Array<OrderOrder>>;
  where: InputMaybe<OrderWhereInput>;
};


export type QueryOrderedProductExportArgs = {
  after: InputMaybe<Scalars['Cursor']['input']>;
  before: InputMaybe<Scalars['Cursor']['input']>;
  excelUrl: InputMaybe<Scalars['String']['input']>;
  fileType: Scalars['String']['input'];
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  orderBy: InputMaybe<Array<OrderedProductOrder>>;
  where: InputMaybe<OrderedProductWhereInput>;
};


export type QueryOrderedProductQueryArgs = {
  after: InputMaybe<Scalars['Cursor']['input']>;
  before: InputMaybe<Scalars['Cursor']['input']>;
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  orderBy: InputMaybe<Array<OrderedProductOrder>>;
  where: InputMaybe<OrderedProductWhereInput>;
};


export type QueryProductExportArgs = {
  after: InputMaybe<Scalars['Cursor']['input']>;
  before: InputMaybe<Scalars['Cursor']['input']>;
  excelUrl: InputMaybe<Scalars['String']['input']>;
  fileType: Scalars['String']['input'];
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  orderBy: InputMaybe<Array<ProductOrder>>;
  where: InputMaybe<ProductWhereInput>;
};


export type QueryProductImagesExportArgs = {
  after: InputMaybe<Scalars['Cursor']['input']>;
  before: InputMaybe<Scalars['Cursor']['input']>;
  excelUrl: InputMaybe<Scalars['String']['input']>;
  fileType: Scalars['String']['input'];
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  orderBy: InputMaybe<Array<ProductImagesOrder>>;
  where: InputMaybe<ProductImagesWhereInput>;
};


export type QueryProductImagesQueryArgs = {
  after: InputMaybe<Scalars['Cursor']['input']>;
  before: InputMaybe<Scalars['Cursor']['input']>;
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  orderBy: InputMaybe<Array<ProductImagesOrder>>;
  where: InputMaybe<ProductImagesWhereInput>;
};


export type QueryProductQueryArgs = {
  after: InputMaybe<Scalars['Cursor']['input']>;
  before: InputMaybe<Scalars['Cursor']['input']>;
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  orderBy: InputMaybe<Array<ProductOrder>>;
  where: InputMaybe<ProductWhereInput>;
};


export type QueryProductVariantsExportArgs = {
  after: InputMaybe<Scalars['Cursor']['input']>;
  before: InputMaybe<Scalars['Cursor']['input']>;
  excelUrl: InputMaybe<Scalars['String']['input']>;
  fileType: Scalars['String']['input'];
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  orderBy: InputMaybe<Array<ProductVariantsOrder>>;
  where: InputMaybe<ProductVariantsWhereInput>;
};


export type QueryProductVariantsQueryArgs = {
  after: InputMaybe<Scalars['Cursor']['input']>;
  before: InputMaybe<Scalars['Cursor']['input']>;
  first: InputMaybe<Scalars['Int']['input']>;
  last: InputMaybe<Scalars['Int']['input']>;
  orderBy: InputMaybe<Array<ProductVariantsOrder>>;
  where: InputMaybe<ProductVariantsWhereInput>;
};


export type QueryNodeArgs = {
  id: Scalars['ID']['input'];
};


export type QueryNodesArgs = {
  ids: Array<Scalars['ID']['input']>;
};


export type QueryTaskStatusArgs = {
  taskId: Scalars['String']['input'];
};

export type TaskState = {
  __typename?: 'TaskState';
  created_at: Maybe<Scalars['Time']['output']>;
  error: Maybe<Scalars['String']['output']>;
  results: Maybe<Scalars['JSON']['output']>;
  state: Scalars['String']['output'];
  task_id: Scalars['String']['output'];
  ttl: Maybe<Scalars['Int']['output']>;
};

/**
 * UpdateCartProductInput is used for update CartProduct object.
 * Input was generated by ent.
 */
export type UpdateCartProductInput = {
  productID: InputMaybe<Scalars['ID']['input']>;
  quantity: InputMaybe<Scalars['Int']['input']>;
  toDeliver: InputMaybe<Scalars['Boolean']['input']>;
  updatedAt: InputMaybe<Scalars['Time']['input']>;
  userID: InputMaybe<Scalars['ID']['input']>;
  variant: InputMaybe<Scalars['String']['input']>;
};

/**
 * UpdateCouponInput is used for update Coupon object.
 * Input was generated by ent.
 */
export type UpdateCouponInput = {
  couponCode: InputMaybe<Scalars['String']['input']>;
  discountPercentage: InputMaybe<Scalars['Int']['input']>;
  email: InputMaybe<Scalars['String']['input']>;
  redeemed: InputMaybe<Scalars['Boolean']['input']>;
  redeemedOn: InputMaybe<Scalars['Time']['input']>;
  updatedAt: InputMaybe<Scalars['Time']['input']>;
};

/**
 * UpdateMemberInput is used for update Member object.
 * Input was generated by ent.
 */
export type UpdateMemberInput = {
  addInCartProductIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  addOrderIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  addOrderedProductIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  alternatePhoneNumber: InputMaybe<Scalars['String']['input']>;
  city: InputMaybe<Scalars['String']['input']>;
  clearAlternatePhoneNumber: InputMaybe<Scalars['Boolean']['input']>;
  clearCity: InputMaybe<Scalars['Boolean']['input']>;
  clearDeptName: InputMaybe<Scalars['Boolean']['input']>;
  clearEventName: InputMaybe<Scalars['Boolean']['input']>;
  clearHouseNo: InputMaybe<Scalars['Boolean']['input']>;
  clearInCartProducts: InputMaybe<Scalars['Boolean']['input']>;
  clearLandmark: InputMaybe<Scalars['Boolean']['input']>;
  clearOrderedProducts: InputMaybe<Scalars['Boolean']['input']>;
  clearOrders: InputMaybe<Scalars['Boolean']['input']>;
  clearPhoneNumber: InputMaybe<Scalars['Boolean']['input']>;
  clearPincode: InputMaybe<Scalars['Boolean']['input']>;
  clearPlace: InputMaybe<Scalars['Boolean']['input']>;
  clearProfilePicURL: InputMaybe<Scalars['Boolean']['input']>;
  clearStreet: InputMaybe<Scalars['Boolean']['input']>;
  deptName: InputMaybe<Scalars['String']['input']>;
  email: InputMaybe<Scalars['String']['input']>;
  eventName: InputMaybe<Scalars['String']['input']>;
  houseNo: InputMaybe<Scalars['String']['input']>;
  landmark: InputMaybe<Scalars['String']['input']>;
  name: InputMaybe<Scalars['String']['input']>;
  phoneNumber: InputMaybe<Scalars['String']['input']>;
  pincode: InputMaybe<Scalars['String']['input']>;
  place: InputMaybe<Scalars['String']['input']>;
  profilePicURL: InputMaybe<Scalars['String']['input']>;
  removeInCartProductIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  removeOrderIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  removeOrderedProductIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  role: InputMaybe<MemberRole>;
  street: InputMaybe<Scalars['String']['input']>;
  updatedAt: InputMaybe<Scalars['Time']['input']>;
};

/**
 * UpdateOrderInput is used for update Order object.
 * Input was generated by ent.
 */
export type UpdateOrderInput = {
  addOrderedProductIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  alternatePhoneNumber: InputMaybe<Scalars['String']['input']>;
  city: InputMaybe<Scalars['String']['input']>;
  clearAlternatePhoneNumber: InputMaybe<Scalars['Boolean']['input']>;
  clearCity: InputMaybe<Scalars['Boolean']['input']>;
  clearHouseNo: InputMaybe<Scalars['Boolean']['input']>;
  clearLandmark: InputMaybe<Scalars['Boolean']['input']>;
  clearOrderedProducts: InputMaybe<Scalars['Boolean']['input']>;
  clearPhoneNumber: InputMaybe<Scalars['Boolean']['input']>;
  clearPincode: InputMaybe<Scalars['Boolean']['input']>;
  clearPlace: InputMaybe<Scalars['Boolean']['input']>;
  clearStreet: InputMaybe<Scalars['Boolean']['input']>;
  email: InputMaybe<Scalars['String']['input']>;
  houseNo: InputMaybe<Scalars['String']['input']>;
  landmark: InputMaybe<Scalars['String']['input']>;
  orderDate: InputMaybe<Scalars['Time']['input']>;
  paidAmount: InputMaybe<Scalars['Float']['input']>;
  phoneNumber: InputMaybe<Scalars['String']['input']>;
  pincode: InputMaybe<Scalars['String']['input']>;
  place: InputMaybe<Scalars['String']['input']>;
  removeOrderedProductIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  street: InputMaybe<Scalars['String']['input']>;
  updatedAt: InputMaybe<Scalars['Time']['input']>;
  userID: InputMaybe<Scalars['ID']['input']>;
};

/**
 * UpdateOrderedProductInput is used for update OrderedProduct object.
 * Input was generated by ent.
 */
export type UpdateOrderedProductInput = {
  orderID: InputMaybe<Scalars['ID']['input']>;
  productID: InputMaybe<Scalars['ID']['input']>;
  quantity: InputMaybe<Scalars['Int']['input']>;
  status: InputMaybe<Scalars['String']['input']>;
  toDeliver: InputMaybe<Scalars['Boolean']['input']>;
  updatedAt: InputMaybe<Scalars['Time']['input']>;
  userID: InputMaybe<Scalars['ID']['input']>;
  variant: InputMaybe<Scalars['String']['input']>;
};

/**
 * UpdateProductImagesInput is used for update ProductImages object.
 * Input was generated by ent.
 */
export type UpdateProductImagesInput = {
  imageURL: InputMaybe<Scalars['String']['input']>;
  productID: InputMaybe<Scalars['ID']['input']>;
  updatedAt: InputMaybe<Scalars['Time']['input']>;
};

/**
 * UpdateProductInput is used for update Product object.
 * Input was generated by ent.
 */
export type UpdateProductInput = {
  addImageIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  addInCartProductIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  addOrderedProductIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  addVariantIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  category: InputMaybe<ProductCategory>;
  clearDescription: InputMaybe<Scalars['Boolean']['input']>;
  clearImages: InputMaybe<Scalars['Boolean']['input']>;
  clearInCartProducts: InputMaybe<Scalars['Boolean']['input']>;
  clearOrderedProducts: InputMaybe<Scalars['Boolean']['input']>;
  clearVariants: InputMaybe<Scalars['Boolean']['input']>;
  description: InputMaybe<Scalars['String']['input']>;
  isDeliverable: InputMaybe<Scalars['Boolean']['input']>;
  name: InputMaybe<Scalars['String']['input']>;
  price: InputMaybe<Scalars['String']['input']>;
  removeImageIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  removeInCartProductIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  removeOrderedProductIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  removeVariantIDs: InputMaybe<Array<Scalars['ID']['input']>>;
  updatedAt: InputMaybe<Scalars['Time']['input']>;
  weight: InputMaybe<Scalars['Int']['input']>;
};

/**
 * UpdateProductVariantsInput is used for update ProductVariants object.
 * Input was generated by ent.
 */
export type UpdateProductVariantsInput = {
  productID: InputMaybe<Scalars['ID']['input']>;
  quantity: InputMaybe<Scalars['Int']['input']>;
  updatedAt: InputMaybe<Scalars['Time']['input']>;
  variant: InputMaybe<Scalars['String']['input']>;
};
